* Manual

** Usage
*** Trash

To delete files in dired, use =#'tr-dired-trash-marked-files=. If
no files are marked, it trashes the file at point any way. While
a file is trashed, the file is moved under =*tr-store*=, with this
action recorded to the database =*tr-db*=.

To undo the very last action, use =#'tr-undo!=. Notice that this
function is almost inverse to itself.

*** Retrieve

To retrieve a trash, simply call =#'tr-undo-order= on an =order=. The
user can specify an performed =order= by first listing out the
records, specify a record, and call =#'tr-record-order= on that
record.

To list all records, see =#'tr-ls-all-records= below.

#+begin_src emacs-lisp
(defun tr-ls-records-that (predicate)
  "Return the list of records that satisfy PREDICATE."
  (-filter predicate
           (ignore-errors
             (read (concat "(" (f-read-text *tr-db* 'utf-8) ")")))))

(defun tr-ls-all-records ()
  "Return all records from the database *TR-DB*"
  (tr-ls-records-that (lambda (dummy) t)))
#+end_src

*** Purge

To purge database and the trash store, use =#'tr-purge=. This is a
function that intakes a time predicate. All information that
satisfies the time predicate will be removed completely. The
users can also write their own time predicates and feed into the
purger =#'tr-purge=. An example usage is given in =tr-purge.el=:

#+begin_src emacs-lisp
(defun tr-purge-before-N-seconds-ago (N)
  (let ((pred (lambda (time)
                (> (ts-diff (ts-now) time) N))))
    (tr-purge pred)))

(defun tr-purge-before-N-days-ago (N)
  (tr-purge-before-N-seconds-ago (* N 60 60 24)))
#+end_src

** Internals

*** variables

=*tr-root-dir*=, =*tr-store*=, and =*tr-db*=.

*** structures

#+begin_src emacs-lisp
(defstruct tr-order
  from to)

(defstruct tr-record
  ts order status memo)
#+end_src

An =order= contains a =FROM= slot and a =TO= slot, as in the code block
above. A performance of an =order= means to overwrite the =FROM= file
to the =TO= file. An =order= can be performed by =#'tr-perform-order=
or undone by =#'tr-undo-order=. Upon any performance/undoing, a
=record= is written in the database =*tr-db*=.

* Todo List

** Working..

+ Make a better retrieval experience..
+ Get used to dired, start using it, and add nice GIFs:

  1. Delete marked files.

  2. Delete the file at point.

  3. Undo!

  4. Retrieve a trash by fuzzy search.

  5. Purge information and database.

** Contribution

+ Make a better customizing experience for the users.
+ Make good keybindings that are compatible with doomemacs and
  dired.
